parameters:
    database_driver: "%env(SYLIUS_DATABASE_DRIVER)%"
    database_host: "%env(SYLIUS_DATABASE_HOST)%"
    database_port: "%env(SYLIUS_DATABASE_PORT)%"
    database_name: "%env(SYLIUS_DATABASE_NAME)%"
    database_user: "%env(SYLIUS_DATABASE_USER)%"
    database_password: "%env(SYLIUS_DATABASE_PASSWORD)%"

    mailer_transport: "%env(SYLIUS_MAILER_TRANSPORT)%"
    mailer_host: "%env(SYLIUS_MAILER_HOST)%"
    mailer_user: "%env(SYLIUS_MAILER_USER)%"
    mailer_password: "%env(SYLIUS_MAILER_PASSWORD)%"
    mailer_port: "%env(SYLIUS_MAILER_PORT)%"
    mailer_encryption: "%env(SYLIUS_MAILER_ENCRYPTION)%"

    secret: "%env(SYLIUS_SECRET)"

    memcached_host: "%env(SYLIUS_MEMCACHED_HOST)%"
    memcached_port: "%env(SYLIUS_MEMCACHED_PORT)%"
    memcached_prefix: "%env(SYLIUS_MEMCACHED_PREFIX)%"
    memcached_expire: "%env(SYLIUS_MEMCACHED_EXPIRE)%"

    # Fallback values (used if environmental variables are not set)
    env(SYLIUS_DATABASE_DRIVER): pdo_mysql
    env(SYLIUS_DATABASE_HOST): 127.0.0.1
    env(SYLIUS_DATABASE_PORT): 3306
    env(SYLIUS_DATABASE_NAME): sylius
    env(SYLIUS_DATABASE_USER): root
    env(SYLIUS_DATABASE_PASSWORD): ~

    env(SYLIUS_MAILER_TRANSPORT): smtp
    env(SYLIUS_MAILER_HOST): 127.0.0.1
    env(SYLIUS_MAILER_USER): ~
    env(SYLIUS_MAILER_PASSWORD): ~
    env(SYLIUS_MAILER_PORT): 465
    env(SYLIUS_MAILER_ENCRYPTION): ssl

    env(SYLIUS_SECRET): EDITME

    env(SYLIUS_MEMCACHED_HOST): 127.0.0.1
    env(SYLIUS_MEMCACHED_PORT): 11211
    env(SYLIUS_MEMCACHED_PREFIX): highlite2_sylius_
    env(SYLIUS_MEMCACHED_EXPIRE): 14400
