version: '2'

volumes:

  highlite2-sylius-composer-cache:
    external: true

  highlite2-sylius-node-modules:
    external: true

services:

  builder:
    build:
      context: ../../
      dockerfile: ci/release/builder/Dockerfile
    volumes:
      - highlite2-sylius-composer-cache:/var/www/.composer
      - highlite2-sylius-node-modules:/var/www/html/node_modules

  sylius-backend:
    build:
      context: ../../
      dockerfile: ci/release/backend/Dockerfile

  sylius-static:
    build:
      context: ../../
      dockerfile: ci/release/static/Dockerfile